//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace DOJO.ServicoCalculo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServicoCalculo.Calculos")]
    public interface Calculos {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Calculos/DoWork", ReplyAction="urn:Calculos/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Calculos/PrimeiroDia", ReplyAction="urn:Calculos/PrimeiroDiaResponse")]
        System.IAsyncResult BeginPrimeiroDia(System.AsyncCallback callback, object asyncState);
        
        string EndPrimeiroDia(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Calculos/PrimeiroAeroporto", ReplyAction="urn:Calculos/PrimeiroAeroportoResponse")]
        System.IAsyncResult BeginPrimeiroAeroporto(System.AsyncCallback callback, object asyncState);
        
        string EndPrimeiroAeroporto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Calculos/TodosAeroportos", ReplyAction="urn:Calculos/TodosAeroportosResponse")]
        System.IAsyncResult BeginTodosAeroportos(System.AsyncCallback callback, object asyncState);
        
        string EndTodosAeroportos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Calculos/DiasTodosAeroportos", ReplyAction="urn:Calculos/DiasTodosAeroportosResponse")]
        System.IAsyncResult BeginDiasTodosAeroportos(System.AsyncCallback callback, object asyncState);
        
        int EndDiasTodosAeroportos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Calculos/DiasPrimeiroAeroporto", ReplyAction="urn:Calculos/DiasPrimeiroAeroportoResponse")]
        System.IAsyncResult BeginDiasPrimeiroAeroporto(System.AsyncCallback callback, object asyncState);
        
        int EndDiasPrimeiroAeroporto(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculosChannel : DOJO.ServicoCalculo.Calculos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimeiroDiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PrimeiroDiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimeiroAeroportoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PrimeiroAeroportoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodosAeroportosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TodosAeroportosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiasTodosAeroportosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DiasTodosAeroportosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiasPrimeiroAeroportoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DiasPrimeiroAeroportoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculosClient : System.ServiceModel.ClientBase<DOJO.ServicoCalculo.Calculos>, DOJO.ServicoCalculo.Calculos {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginPrimeiroDiaDelegate;
        
        private EndOperationDelegate onEndPrimeiroDiaDelegate;
        
        private System.Threading.SendOrPostCallback onPrimeiroDiaCompletedDelegate;
        
        private BeginOperationDelegate onBeginPrimeiroAeroportoDelegate;
        
        private EndOperationDelegate onEndPrimeiroAeroportoDelegate;
        
        private System.Threading.SendOrPostCallback onPrimeiroAeroportoCompletedDelegate;
        
        private BeginOperationDelegate onBeginTodosAeroportosDelegate;
        
        private EndOperationDelegate onEndTodosAeroportosDelegate;
        
        private System.Threading.SendOrPostCallback onTodosAeroportosCompletedDelegate;
        
        private BeginOperationDelegate onBeginDiasTodosAeroportosDelegate;
        
        private EndOperationDelegate onEndDiasTodosAeroportosDelegate;
        
        private System.Threading.SendOrPostCallback onDiasTodosAeroportosCompletedDelegate;
        
        private BeginOperationDelegate onBeginDiasPrimeiroAeroportoDelegate;
        
        private EndOperationDelegate onEndDiasPrimeiroAeroportoDelegate;
        
        private System.Threading.SendOrPostCallback onDiasPrimeiroAeroportoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CalculosClient() {
        }
        
        public CalculosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<PrimeiroDiaCompletedEventArgs> PrimeiroDiaCompleted;
        
        public event System.EventHandler<PrimeiroAeroportoCompletedEventArgs> PrimeiroAeroportoCompleted;
        
        public event System.EventHandler<TodosAeroportosCompletedEventArgs> TodosAeroportosCompleted;
        
        public event System.EventHandler<DiasTodosAeroportosCompletedEventArgs> DiasTodosAeroportosCompleted;
        
        public event System.EventHandler<DiasPrimeiroAeroportoCompletedEventArgs> DiasPrimeiroAeroportoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DOJO.ServicoCalculo.Calculos.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void DOJO.ServicoCalculo.Calculos.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DOJO.ServicoCalculo.Calculos)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((DOJO.ServicoCalculo.Calculos)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DOJO.ServicoCalculo.Calculos.BeginPrimeiroDia(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPrimeiroDia(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string DOJO.ServicoCalculo.Calculos.EndPrimeiroDia(System.IAsyncResult result) {
            return base.Channel.EndPrimeiroDia(result);
        }
        
        private System.IAsyncResult OnBeginPrimeiroDia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DOJO.ServicoCalculo.Calculos)(this)).BeginPrimeiroDia(callback, asyncState);
        }
        
        private object[] OnEndPrimeiroDia(System.IAsyncResult result) {
            string retVal = ((DOJO.ServicoCalculo.Calculos)(this)).EndPrimeiroDia(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPrimeiroDiaCompleted(object state) {
            if ((this.PrimeiroDiaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PrimeiroDiaCompleted(this, new PrimeiroDiaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PrimeiroDiaAsync() {
            this.PrimeiroDiaAsync(null);
        }
        
        public void PrimeiroDiaAsync(object userState) {
            if ((this.onBeginPrimeiroDiaDelegate == null)) {
                this.onBeginPrimeiroDiaDelegate = new BeginOperationDelegate(this.OnBeginPrimeiroDia);
            }
            if ((this.onEndPrimeiroDiaDelegate == null)) {
                this.onEndPrimeiroDiaDelegate = new EndOperationDelegate(this.OnEndPrimeiroDia);
            }
            if ((this.onPrimeiroDiaCompletedDelegate == null)) {
                this.onPrimeiroDiaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPrimeiroDiaCompleted);
            }
            base.InvokeAsync(this.onBeginPrimeiroDiaDelegate, null, this.onEndPrimeiroDiaDelegate, this.onPrimeiroDiaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DOJO.ServicoCalculo.Calculos.BeginPrimeiroAeroporto(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPrimeiroAeroporto(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string DOJO.ServicoCalculo.Calculos.EndPrimeiroAeroporto(System.IAsyncResult result) {
            return base.Channel.EndPrimeiroAeroporto(result);
        }
        
        private System.IAsyncResult OnBeginPrimeiroAeroporto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DOJO.ServicoCalculo.Calculos)(this)).BeginPrimeiroAeroporto(callback, asyncState);
        }
        
        private object[] OnEndPrimeiroAeroporto(System.IAsyncResult result) {
            string retVal = ((DOJO.ServicoCalculo.Calculos)(this)).EndPrimeiroAeroporto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPrimeiroAeroportoCompleted(object state) {
            if ((this.PrimeiroAeroportoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PrimeiroAeroportoCompleted(this, new PrimeiroAeroportoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PrimeiroAeroportoAsync() {
            this.PrimeiroAeroportoAsync(null);
        }
        
        public void PrimeiroAeroportoAsync(object userState) {
            if ((this.onBeginPrimeiroAeroportoDelegate == null)) {
                this.onBeginPrimeiroAeroportoDelegate = new BeginOperationDelegate(this.OnBeginPrimeiroAeroporto);
            }
            if ((this.onEndPrimeiroAeroportoDelegate == null)) {
                this.onEndPrimeiroAeroportoDelegate = new EndOperationDelegate(this.OnEndPrimeiroAeroporto);
            }
            if ((this.onPrimeiroAeroportoCompletedDelegate == null)) {
                this.onPrimeiroAeroportoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPrimeiroAeroportoCompleted);
            }
            base.InvokeAsync(this.onBeginPrimeiroAeroportoDelegate, null, this.onEndPrimeiroAeroportoDelegate, this.onPrimeiroAeroportoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DOJO.ServicoCalculo.Calculos.BeginTodosAeroportos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTodosAeroportos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string DOJO.ServicoCalculo.Calculos.EndTodosAeroportos(System.IAsyncResult result) {
            return base.Channel.EndTodosAeroportos(result);
        }
        
        private System.IAsyncResult OnBeginTodosAeroportos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DOJO.ServicoCalculo.Calculos)(this)).BeginTodosAeroportos(callback, asyncState);
        }
        
        private object[] OnEndTodosAeroportos(System.IAsyncResult result) {
            string retVal = ((DOJO.ServicoCalculo.Calculos)(this)).EndTodosAeroportos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTodosAeroportosCompleted(object state) {
            if ((this.TodosAeroportosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TodosAeroportosCompleted(this, new TodosAeroportosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TodosAeroportosAsync() {
            this.TodosAeroportosAsync(null);
        }
        
        public void TodosAeroportosAsync(object userState) {
            if ((this.onBeginTodosAeroportosDelegate == null)) {
                this.onBeginTodosAeroportosDelegate = new BeginOperationDelegate(this.OnBeginTodosAeroportos);
            }
            if ((this.onEndTodosAeroportosDelegate == null)) {
                this.onEndTodosAeroportosDelegate = new EndOperationDelegate(this.OnEndTodosAeroportos);
            }
            if ((this.onTodosAeroportosCompletedDelegate == null)) {
                this.onTodosAeroportosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTodosAeroportosCompleted);
            }
            base.InvokeAsync(this.onBeginTodosAeroportosDelegate, null, this.onEndTodosAeroportosDelegate, this.onTodosAeroportosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DOJO.ServicoCalculo.Calculos.BeginDiasTodosAeroportos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDiasTodosAeroportos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int DOJO.ServicoCalculo.Calculos.EndDiasTodosAeroportos(System.IAsyncResult result) {
            return base.Channel.EndDiasTodosAeroportos(result);
        }
        
        private System.IAsyncResult OnBeginDiasTodosAeroportos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DOJO.ServicoCalculo.Calculos)(this)).BeginDiasTodosAeroportos(callback, asyncState);
        }
        
        private object[] OnEndDiasTodosAeroportos(System.IAsyncResult result) {
            int retVal = ((DOJO.ServicoCalculo.Calculos)(this)).EndDiasTodosAeroportos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDiasTodosAeroportosCompleted(object state) {
            if ((this.DiasTodosAeroportosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DiasTodosAeroportosCompleted(this, new DiasTodosAeroportosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DiasTodosAeroportosAsync() {
            this.DiasTodosAeroportosAsync(null);
        }
        
        public void DiasTodosAeroportosAsync(object userState) {
            if ((this.onBeginDiasTodosAeroportosDelegate == null)) {
                this.onBeginDiasTodosAeroportosDelegate = new BeginOperationDelegate(this.OnBeginDiasTodosAeroportos);
            }
            if ((this.onEndDiasTodosAeroportosDelegate == null)) {
                this.onEndDiasTodosAeroportosDelegate = new EndOperationDelegate(this.OnEndDiasTodosAeroportos);
            }
            if ((this.onDiasTodosAeroportosCompletedDelegate == null)) {
                this.onDiasTodosAeroportosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDiasTodosAeroportosCompleted);
            }
            base.InvokeAsync(this.onBeginDiasTodosAeroportosDelegate, null, this.onEndDiasTodosAeroportosDelegate, this.onDiasTodosAeroportosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DOJO.ServicoCalculo.Calculos.BeginDiasPrimeiroAeroporto(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDiasPrimeiroAeroporto(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int DOJO.ServicoCalculo.Calculos.EndDiasPrimeiroAeroporto(System.IAsyncResult result) {
            return base.Channel.EndDiasPrimeiroAeroporto(result);
        }
        
        private System.IAsyncResult OnBeginDiasPrimeiroAeroporto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DOJO.ServicoCalculo.Calculos)(this)).BeginDiasPrimeiroAeroporto(callback, asyncState);
        }
        
        private object[] OnEndDiasPrimeiroAeroporto(System.IAsyncResult result) {
            int retVal = ((DOJO.ServicoCalculo.Calculos)(this)).EndDiasPrimeiroAeroporto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDiasPrimeiroAeroportoCompleted(object state) {
            if ((this.DiasPrimeiroAeroportoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DiasPrimeiroAeroportoCompleted(this, new DiasPrimeiroAeroportoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DiasPrimeiroAeroportoAsync() {
            this.DiasPrimeiroAeroportoAsync(null);
        }
        
        public void DiasPrimeiroAeroportoAsync(object userState) {
            if ((this.onBeginDiasPrimeiroAeroportoDelegate == null)) {
                this.onBeginDiasPrimeiroAeroportoDelegate = new BeginOperationDelegate(this.OnBeginDiasPrimeiroAeroporto);
            }
            if ((this.onEndDiasPrimeiroAeroportoDelegate == null)) {
                this.onEndDiasPrimeiroAeroportoDelegate = new EndOperationDelegate(this.OnEndDiasPrimeiroAeroporto);
            }
            if ((this.onDiasPrimeiroAeroportoCompletedDelegate == null)) {
                this.onDiasPrimeiroAeroportoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDiasPrimeiroAeroportoCompleted);
            }
            base.InvokeAsync(this.onBeginDiasPrimeiroAeroportoDelegate, null, this.onEndDiasPrimeiroAeroportoDelegate, this.onDiasPrimeiroAeroportoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DOJO.ServicoCalculo.Calculos CreateChannel() {
            return new CalculosClientChannel(this);
        }
        
        private class CalculosClientChannel : ChannelBase<DOJO.ServicoCalculo.Calculos>, DOJO.ServicoCalculo.Calculos {
            
            public CalculosClientChannel(System.ServiceModel.ClientBase<DOJO.ServicoCalculo.Calculos> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginPrimeiroDia(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("PrimeiroDia", _args, callback, asyncState);
                return _result;
            }
            
            public string EndPrimeiroDia(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("PrimeiroDia", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPrimeiroAeroporto(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("PrimeiroAeroporto", _args, callback, asyncState);
                return _result;
            }
            
            public string EndPrimeiroAeroporto(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("PrimeiroAeroporto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTodosAeroportos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TodosAeroportos", _args, callback, asyncState);
                return _result;
            }
            
            public string EndTodosAeroportos(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("TodosAeroportos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDiasTodosAeroportos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DiasTodosAeroportos", _args, callback, asyncState);
                return _result;
            }
            
            public int EndDiasTodosAeroportos(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("DiasTodosAeroportos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDiasPrimeiroAeroporto(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DiasPrimeiroAeroporto", _args, callback, asyncState);
                return _result;
            }
            
            public int EndDiasPrimeiroAeroporto(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("DiasPrimeiroAeroporto", _args, result)));
                return _result;
            }
        }
    }
}
